apiVersion: v1
kind: ConfigMap
metadata:
  name: chatwoot-config
data:
  # Application Configuration
  RAILS_ENV: "production"
  NODE_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "true"
  BUNDLE_WITHOUT: ""
  EXECJS_RUNTIME: "Node"
  INSTALLATION_NAME: "Chatwoot"
  FRONTEND_URL: "https://cx.alooo.ai"
  DOMAIN: "cx.alooo.ai"

  # Database Configuration
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"

  # Redis Configuration
  REDIS_URL: "${REDIS_URL}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"

  # SMTP Configuration
  SMTP_ADDRESS: "chatwoot-mailhog"
  SMTP_PORT: "1025"
  SMTP_DOMAIN: "localhost"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_AUTHENTICATION: "plain"
  SMTP_ENABLE_STARTTLS_AUTO: "true"

  # Vite Configuration
  VITE_DEV_SERVER_HOST: "0.0.0.0"
  VITE_APP_URL: "https://cx.alooo.ai"

  # Add other environment variables as needed
