apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatwoot-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  tls:
      secretName: chatwoot-tls
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatwoot-rails
                port:
                  number: 3000
          - path: /cable
            pathType: Prefix
            backend:
              service:
                name: chatwoot-rails
                port:
                  number: 3000
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: chatwoot-vite
                port:
                  number: 3036
          - path: /mailhog
            pathType: Prefix
            backend:
              service:
                name: chatwoot-mailhog
                port:
                  number: 8025 